title: "Documentation"
description: "Documentation portal for my R packages"
url: "https://cherylisabella.github.io"
baseurl: "/docs"
remote_theme: just-the-docs/just-the-docs

markdown: kramdown
color_scheme: dark
search_enabled: true

aux_links:
  "GitHub":
    - "https://github.com/cherylisabella"

footer_content: "Developed by Cheryl Isabella Lim"

exclude:
  - README.md
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore
